compile:
  stage: build
  image: maven:3.5-slim
  script:
   - mvn clean package

deploy-node1:
  stage: deploy
  image: maven:3.5.3-jdk-10
  script:
   -   mvn deploy -P wildfly-deploy-node1 --settings settings.xml
deploy-node2:
  stage: deploy
  image: maven:3.5.3-jdk-10
  script:
   -   mvn deploy -P wildfly-deploy-node2 --settings settings.xml

