stages:
  - test
  - package
  - deploy

cache:
  paths:
    - .m2/

image: maven:3.5-slim

variables:
  MAVEN_OPTS: -Dmaven.repo.local=${CI_PROJECT_DIR}/.m2

test:
  stage: test
  script:
   - mvn sonar:sonar -Dsonar.login=admin -Dsonar.password=admin

deploy-nexus:
  stage: package
  script:
   - mvn deploy --settings settings.xml

deploy-wildfly:
  stage: deploy
  image: gabylan/debian-wget
  script:
   - wget http://192.168.99.100:8580/nexus/content/repositories/releases/org/samples/wildfly/clustering/http/1.3/http-1.3.war --output-document=http.war



