cache:
  paths:
    - .m2/

image: maven:3.5-slim

variables:
  MAVEN_OPTS: -Dmaven.repo.local=${CI_PROJECT_DIR}/.m2

test:
  stage: test
  script:
   - mvn sonar:sonar -Dsonar.login=admin -Dsonar.password=admin

deploy-nexus:
  stage: deploy
  script:
   - mvn deploy --settings settings.xml




deploy-node1:
  stage: deploy
  image: maven:3.5.3-jdk-10
  script:
   -   mvn deploy -P wildfly-deploy-node1 --settings settings.xml
deploy-node2:
  stage: deploy
  image: maven:3.5.3-jdk-10
  script:
   -   mvn deploy -P wildfly-deploy-node2 --settings settings.xml

