stages:
  - test
  - package
  - deploy

cache:
  paths:
    - .m2/

image: maven:3.5-slim

variables:
  MAVEN_OPTS: -Dmaven.repo.local=${CI_PROJECT_DIR}/.m2

test:
  stage: test
  script:
   - mvn sonar:sonar -Dsonar.login=admin -Dsonar.password=admin

deploy-nexus:
  stage: deploy
  script:
   - mvn deploy --settings settings.xml



