version: '3'
services:
  node1:
    container_name: node1
    build: 
     context: .
     dockerfile: Dockerfile
     args: 
      NODE: -Djboss.node.name=server1
      NODE_NAME: node1
    ports:
     - "8080:8080"
     - "9990:9990"
    volumes:
     - "/hosthome/gabriel/docker/jboss/wildfly-samples/clustering/http/target:/opt/jboss/wildfly/standalone/deployments"
    networks:
      vpcbr:
        ipv4_address: 10.5.0.2
  node2:
    container_name: node2
    build:
     context: .
     dockerfile: Dockerfile
     args:
      NODE: -Djboss.node.name=server2
      NODE_NAME: node2
    ports:
     - "8081:8080"
     - "9991:9990"
    volumes:
     - "/hosthome/gabriel/docker/jboss/wildfly-samples/clustering/http/target:/opt/jboss/wildfly/standalone/deployments"
    networks:
      vpcbr:
        ipv4_address: 10.5.0.3
  gitlab:
    container_name: gitlab
    image: gitlab/gitlab-ce:10.7.1-ce.0
    hostname: 192.168.99.100
    volumes:
     - "/hosthome/gabriel/docker/jboss/gitlab/config:/etc/gitlab"
     - "/hosthome/gabriel/docker/jboss/gitlab/logs:/var/log/gitlab"
     - "/hosthome/gabriel/docker/jboss/gitlab/data:/var/opt/gitlab"
    ports:
     - "80:80"
  gitlab-runner:
    container_name: gitlab-runner
    image: gitlab/gitlab-runner:v10.7.0
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
  sonar:
    container_name: sonarqube
    image: sonarqube:7.1
    ports:
      - "9000:9000"
  nexus:
     container_name: nexus
     image: sonatype/nexus:2.14.8-01
     ports:
      - "8580:8081"
networks:
 vpcbr:
    driver: bridge
    ipam:
     config:
       - subnet: 10.5.0.0/16 
